export interface TblPos {
  id: string
  storeId: number
  transNo: string
  appVersion: string
  reference: string
  orderShortNumber: string
  orderType: string
  description: string
  consignmentNo: string
  woId?: number
  woReference: string
  technicianId: string
  memberCode?: number
  cashierTransId?: number
  transDate: string
  dueDate?: string
  transTime: string
  taxType: string
  taxInvoiceNo: string
  taxDate?: string
  dineInTax?: number
  discountLoyalty: number
  lastCashback: number
  gettingCashback: number
  discInvoicePercent?: number
  discInvoiceNominal?: number
  qty: number
  total?: number
  discount?: number
  dpp?: number
  ppn?: number
  netto?: number
  change?: number
  paid?: number
  paymentTotal?: number
  returnTotal?: number
  voucherProfit?: number
  creditCardNo: string
  creditCardType: string
  creditCardCharge?: number
  totalCreditCard: number
  rounding: number
  paymentVia: string
  createdAt: Date
  updatedAt: Date
  lastMeter: number
  status: string
  validPayment?: number
  memo: string
  countDuplicate: number
  policeNoId?: number
  printNo: number
  printLimit: number
  createdBy: string
  updatedBy: string
  ignoreFollowUp: string
}
