export interface TblBundling {
  id: number
  isPosHighlight: number
  type: string
  code: string
  name: string
  bundlingCategoryId: number
  startDate: string
  endDate: string
  startHour?: string
  endHour?: string
  availableDate: string
  availableStore: string
  applyMultiple: string
  status: string
  minimumPayment: number
  paymentOption: string
  paymentBankId?: number
  grabCategoryId?: number
  subcategoryId: string
  categoryId: string
  grabCategoryName: string
  description: string
  activeShop: number
  weight: string
  memo: string
  productImage: string
  createdBy: string
  createdAt: Date
  updatedBy?: string
  updatedAt?: Date
  barcode01: string
  alwaysOn: number
  buildComponent: number
  haveTargetPrice: number
  targetRetailPrice: number
  targetCostPrice: number
  pageSize: number
  total: number
  page: number
}
