export interface TblStock {
  id: string
  productCode: string
  productName: string
  barCode01: string
  barCode02: string
  otherName01: string
  otherName02: string
  location01: string
  location02: string
  locationId?: number
  costPrice: number
  ppn?: number
  sellPrice?: number
  sellPricePre?: number
  distPrice01?: number
  distPrice02?: number
  distPrice03?: number
  distPrice04?: number
  distPrice05?: number
  distPrice06?: number
  distPrice07?: number
  distPrice08?: number
  distPrice09?: number
  brandId: number
  categoryId: number
  supplierSource: number
  divisionId: number
  departmentId: number
  subDepartmentId: number
  supplierId?: number
  countryName: string
  isHalal: number
  trackQty?: number
  alertQty?: number
  active: number
  productTag: string
  productBaseTag: string
  isStockOpname: number
  stockOpnameAccount?: number
  isStaging: number
  taxType: string
  exception01: number
  usageTimePeriod?: number
  usageMileage?: number
  productImage: string
  description: string
  dimension: string
  dimensionPack: string
  dimensionBox: string
  weight: string
  activeShop: number
  publishDate?: Date
  grabCategoryId?: number
  grabCategoryName: string
  expressActive: number
  expressItemId?: number
  expressReturnPolicy?: number
  expressCategoryId?: number
  expressCategoryName: string
  expressBrandId?: number
  expressBrandName: string
  expressUploaded: string
  dummyCode: string
  dummyName: string
  createdBy: string
  createdAt: Date
  updatedBy?: string
  updatedAt?: Date
  sectionWidth: string
  aspectRatio: string
  rimDiameter: string
  disc1?: number
  disc2?: number
  disc3?: number
  discount?: number
  listCategory?: ListCategory[]
}

interface ListCategory {
  id: number
  qty: string | number
  code: string
  name: string
}
